version: 2.1
orbs:
  node: circleci/node@4.9.0
  win: circleci/windows@2.3.0

jobs:
  build-linux-amd:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13.2"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Login to Github Packages
          command: |
            npm set //npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}
      - run:
          name: Install Dependencies
          command: yarn install --non-interactive --frozen-lockfile
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot rpm
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Publish
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            yarn run publish

  build-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13.2"
      - restore_cache:
          key: dependency-cache-win-{{ checksum "package.json" }}
      - run:
          name: Login to Github Packages
          command: |
            npm set //npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}
      - run:
          name: Install Dependencies
          command: yarn install --non-interactive --frozen-lockfile
      - save_cache:
          key: dependency-cache-win-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Publish
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            yarn run publish

  build-mac-amd:
    macos:
      xcode: 13.2.1
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13.2"
      - restore_cache:
          key: dependency-cache-macos-{{ checksum "package.json" }}
      - run:
          name: Login to Github Packages
          command: |
            npm set //npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}
      - run:
          name: Install Dependencies
          command: yarn install --non-interactive --frozen-lockfile
      - save_cache:
          key: dependency-cache-macos-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Make Package
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            yarn run make
      - run:
          name: Install Widevine Python Module
          command: python3 -m pip install --upgrade castlabs-evs
      - run:
          name: Widevine Signature
          command: |
            export ACCOUNT_NAME=${CASTLABS_ACCOUNT_NAME}
            export ACCOUNT_PASSWORD=${CASTLABS_ACCOUNT_PASSWORD}
            python3 -m castlabs_evs.account -n reauth -A $ACCOUNT_NAME -P $ACCOUNT_PASSWORD
            python3 -m castlabs_evs.vmp sign-pkg "./out/Kenku FM-darwin-x64/"
      - run:
          name: Import Apple Security Keychain
          command: |
            export CERTIFICATE_P12=certificate.p12;
            echo "${CERT_OSX_P12}"| base64 --decode -o $CERTIFICATE_P12;
            export KEYCHAIN=kenku-fm.keychain;
            security create-keychain -p "${APPLE_KEYCHAIN_PASSWORD}" "$KEYCHAIN";
            security default-keychain -s "$KEYCHAIN";
            security unlock-keychain -p "${APPLE_KEYCHAIN_PASSWORD}" "$KEYCHAIN";
            security import "$CERTIFICATE_P12" -k "$KEYCHAIN" -P "${CERT_PASSWORD}" -A
            security find-identity -v
      - run:
          name: OSX Signature
          no_output_timeout: 30m
          command: |
            export DEBUG=electron-osx-sign*
            npx electron-osx-sign ./out/Kenku\ FM-darwin-x64/Kenku\ FM.app --gatekeeper-access=false --identity="Developer ID Application: Mitchell McCaffrey (${APPLE_DEVELOPER_TEAM_ID})" --hardened-runtime=true --entitlements="entitlements.plist" --entitlements-inherit="entitlements.plist"
      - run:
          name: Zip App
          command: |
            ditto -c -k --sequesterRsrc --keepParent ./out/Kenku FM-darwin-x64/Kenku\ FM.app ./out/Kenku\ FM-darwin-x64/Kenku\ FM.zip
      - run:
          name: Notarize Zip file
          command: |
            export DEVELOPER_EMAIL=${APPLE_DEVELOPER_EMAIL}
            export DEVELOPER_PASSWORD=${APPLE_DEVELOPER_PASSWORD}
            export DEVELOPER_TEAM_ID=${APPLE_DEVELOPER_TEAM_ID}
            xcrun notarytool submit ./out/Kenku\ FM-darwin-x64/Kenku\ FM.zip --apple-id $DEVELOPER_EMAIL --password $DEVELOPER_PASSWORD --team-id $DEVELOPER_TEAM_ID --wait --output-format json
      - run:
          name: Staple
          command: |
            xcrun stapler staple -v ./out/Kenku\ FM-darwin-x64/Kenku\ FM.app
      - run:
          name: Create DMG
          command: |
            
            npx electron-installer-dmg --background=./src/assets/dmg-background.png --icon=./src/assets/setup.icns --out=$MACOS_APP_PATH "./out/Kenku FM-darwin-x64/Kenku FM.app" Kenku\ FM
      - run:
          name: Publish DMG
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            ./publish/script-macos.sh ./out/Kenku\ FM-darwin-x64/Kenku\ FM.dmg $GITHUB_TOKEN $CIRCLE_TAG Kenku.FM-$TAG-x64.dmg

workflows:
  version: 2
  deploy:
    jobs:
      - build-linux-amd:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - build-win:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - build-mac-amd:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
