version: 2.1
orbs:
  node: circleci/node@4.9.0
  win: circleci/windows@2.3.0

executors:
  linux-amd:
    machine:
      image: ubuntu-2004:202111-02

  mac-amd:
    macos:
      xcode: 13.2.1

commands:
  install-npm:
    steps:
      - node/install:
          install-yarn: true
          node-version: "16.13.2"
  
  login-to-github-packages:
    steps:
      - run:
          name: Login to Github Packages
          command: |
            npm set //npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}
  
  install-dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --non-interactive --frozen-lockfile
  
  publish-electron-app:
    steps:
      - run:
          name: Publish
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            yarn run publish

jobs:
  install-npm-linux-amd:
    executor: linux-amd
    working_directory: ~/repo
    steps:
      - install-npm

  restore-cache-linux-amd:
    executor: linux-amd
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  
  github-login-linux-amd:
    executor: linux-amd
    working_directory: ~/repo
    steps: 
      - login-to-github-packages

  install-packages-linux-amd:
    executor: linux-amd
    working_directory: ~/repo
    steps:
      - install-dependencies

  install-linux-packages:
    executor: linux-amd
    working_directory: ~/repo
    steps:
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot rpm

  save-cache-linux-amd:
    executor: linux-amd
    working_directory: ~/repo
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish-electron-app-linux-amd:
    executor: linux-amd
    working_directory: ~/repo
    steps:
      - publish-electron-app

  checkout-linux-amd:
    executor: linux-amd
    steps:
      - checkout

  checkout-win:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout

  install-npm-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - install-npm

  restore-cache-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: dependency-cache-win-{{ checksum "package.json" }}

  github-login-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - login-to-github-packages

  install-packages-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - install-dependencies

  save-cache-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - save_cache:
          key: dependency-cache-win-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish-electron-app-win:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - publish-electron-app

  checkout-mac-amd:
    executor: mac-amd
    steps:
      - checkout

  install-npm-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - install-npm

  restore-cache-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: dependency-cache-macos-{{ checksum "package.json" }}

  github-login-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - login-to-github-packages

  install-packages-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - install-dependencies

  save-cache-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - save_cache:
          key: dependency-cache-macos-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish-electron-app-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - run:
          name: Make Package
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            yarn run make

  install-castlabs-module-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - run:
          name: Install Widevine Python Module
          command: python3 -m pip install --upgrade castlabs-evs

  add-apple-developer-keychain:
    executor: mac-amd
    working_directory: ~/repo
    steps:
      - run:
          name: Import Apple Security Keychain
          command: |
            export CERTIFICATE_P12=certificate.p12;
            echo "${CERT_OSX_P12}"| base64 --decode -o $CERTIFICATE_P12;
            export KEYCHAIN=kenku-fm.keychain;
            security create-keychain -p "${APPLE_KEYCHAIN_PASSWORD}" "$KEYCHAIN";
            security default-keychain -s "$KEYCHAIN";
            security unlock-keychain -p "${APPLE_KEYCHAIN_PASSWORD}" "$KEYCHAIN";
            security import "$CERTIFICATE_P12" -k "$KEYCHAIN" -P "${CERT_PASSWORD}" -A
            security set-key-partition-list -S apple-tool:,apple: -s -k "$APPLE_KEYCHAIN_PASSWORD" "$KEYCHAIN"

  sign-electron-app-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    environment:
      KENKU_FM_MAC_X64_PATH: "./out/Kenku\ FM-darwin-x64"
    steps:
      - run:
          name: Widevine Signature
          command: |
            python3 -m castlabs_evs.account -n reauth -A "$CASTLABS_ACCOUNT_NAME" -P "$CASTLABS_ACCOUNT_PASSWORD"
            python3 -m castlabs_evs.vmp sign-pkg "$KENKU_FM_MAC_X64_PATH"
      - run:
          name: OSX Signature
          command: |
            npx electron-osx-sign "$KENKU_FM_MAC_X64_PATH"/ --gatekeeper-assess=false --identity="Developer ID Application: Mitchell McCaffrey: (${APPLE_DEVELOPER_TEAM_ID})" --hardened-runtime=true --entitlements="entitlements.plist" --entitlements-inherit="entitlements.plist"
      - run:
          name: Zip App
          command: ditto -c -k --sequesterRsrc --keepParent "$KENKU_FM_MAC_X64_PATH"/Kenku\ FM.app "$KENKU_FM_MAC_X64_PATH"/Kenku\ FM.zip
      - run:
          name: Notarize Zip file
          command: xcrun notarytool submit "$KENKU_FM_MAC_X64_PATH"/Kenku\ FM.zip --apple-id "$APPLE_DEVELOPER_EMAIL" --password "$APPLE_DEVELOPER_PASSWORD" --team-id "$APPLE_DEVELOPER_TEAM_ID" --wait --output-format json
      - run:
          name: Staple
          command: xcrun stapler staple -v "$KENKU_FM_MAC_X64_PATH"/Kenku\ FM.app

  create-dmg-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    environment:
      KENKU_FM_MAC_X64_PATH: "./out/Kenku\ FM-darwin-x64"
    steps: 
      - run:
          name: Create DMG
          command: |
            npx electron-installer-dmg --background=./src/assets/dmg-background.png --icon=./src/assets/setup.icns --out="$KENKU_FM_MAC_X64_PATH"/ "$KENKU_FM_MAC_X64_PATH"/Kenku\ FM.app Kenku\ FM

  publish-dmg-mac-amd:
    executor: mac-amd
    working_directory: ~/repo
    environment:
      KENKU_FM_MAC_X64_PATH: "./out/Kenku\ FM-darwin-x64"
    steps:
      - run:
          name: Publish DMG
          command: |
            export GITHUB_TOKEN=${GITHUB_REPO_TOKEN}
            ./publish/script-macos.sh "$KENKU_FM_MAC_X64_PATH"/Kenku\ FM.dmg $GITHUB_TOKEN $CIRCLE_TAG Kenku.FM-$CIRCLE_TAG-x64.dmg

workflows:
  version: 2
  deploy-linux-amd:
    jobs:
      - install-npm-linux-amd:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - install-linux-packages:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - checkout-linux-amd:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - github-login-linux-amd:
          requires:
            - install-npm-linux-amd
      - restore-cache-linux-amd:
          requires:
            - install-npm-linux-amd
            - checkout-linux-amd
      - install-packages-linux-amd:
          requires:
            - restore-cache-linux-amd
            - github-login-linux-amd
      - publish-electron-app-linux-amd:
          requires:
            - install-linux-packages
            - install-packages-linux-amd

  deploy-win:
    jobs:
      - install-npm-win:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - checkout-win:
          filters:
            tags:
              ignore: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - github-login-win:
          requires:
            - install-npm-win
      - restore-cache-win:
          requires:
            - install-npm-win
            - checkout-win
      - install-packages-win:
          requires:
            - restore-cache-win
            - github-login-win
      - publish-electron-app-win:
          requires:
            - install-packages-win
  deploy-mac-amd:
    jobs:
      - install-npm-mac-amd:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - checkout-mac-amd:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - install-castlabs-module-mac-amd:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - add-apple-developer-keychain:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - github-login-mac-amd:
          requires:
            - install-npm-mac-amd
      - restore-cache-mac-amd:
          requires:
            - install-npm-mac-amd
            - checkout-mac-amd
      - install-packages-mac-amd:
          requires:
            - restore-cache-mac-amd
            - github-login-mac-amd
      - publish-electron-app-mac-amd:
          requires:
            - install-packages-mac-amd
      - sign-electron-app-mac-amd:
          requires:
            - add-apple-developer-keychain
            - install-castlabs-module-mac-amd
            - publish-electron-app-mac-amd
      - create-dmg-mac-amd:
          requires:
            - sign-electron-app-mac-amd
      - publish-dmg-mac-amd:
          requires:
            - create-dmg-mac-amd
